### ISSUE TITLE
undefined in global.js

### ISSUE THREAD

**Issue by amelon** [codylindley/simple-frontend-boilerplate#5]
I like your project.

in global.js you use `undefined` param, but to get a true `undefined` param it must be placed as last parameter and omitted during invocation.

eg:

```
window.sfb.globals = function(win, doc, $, _, Modernizr, undefined){
...
your code with a true undefined
...
}.call(window.sfb, window, document, jQuery, _, Modernizr /*, omitted undefined here */);
```

You can look at following link for explanation:
http://stackoverflow.com/questions/6400632/why-do-we-need-to-pass-in-window-and-undefined-into-this-jquery-plugin

**Comment by codylindley** [comment]
Yup. Doh. Thanks. Fixing.
