### ISSUE TITLE
expand/clarify last paragraph in readme

### ISSUE THREAD

**Issue by leoj3n** [codylindley/simple-frontend-boilerplate#6]
The following paragraph (from the readme) could use some work; it's confusing to read.

> When you are running the code locally the html pages, using yepnope, load the CSS and HTML individually. When you are not running the webpages from a localhost the webpages attempt to use the minified files. As well, the handlebar files are compiled at run time instead of being pre-compiled.

Just IMHO. Feel free to close this issue at will.

**Comment by dcorb** [comment]
Agree.

**Comment by codylindley** [comment]
Agree.
