### ISSUE TITLE
Bower as a dependence

### ISSUE THREAD

**Issue by dcardosods** [codylindley/simple-frontend-boilerplate#9]
When run `npm install`, Bower is installed locally, but is necessary a global installation.

What do you think about include a pre-install script to do it?
Something like this:

``` json
"scripts": {
  "preinstall": "npm install -g bower"
}
```

**Comment by codylindley** [comment]
added -g to initial npm install

**Comment by dcardosods** [comment]
This doesn't works, see https://github.com/isaacs/npm/issues/757.

A option is instruct in the README a explicit instalation of the bower `npm install -g bower`, and remove it from dependencies.

**Comment by codylindley** [comment]
Roger.

**Comment by codylindley** [comment]
added as a step in readme. Thanks for the input.
